### ISSUE TITLE
[BUG] Lavalink connection closes with error 1006.

### ISSUE THREAD

**Issue by 0zul** [0zul/LavalinkOnHeroku#3]
**Describe the bug**
Lavalink server closes with websocket error code 1006.

**Expected behavior**
Lavalink server connection shouldn't be closing at all.

**Actual behavior**
Lavalink websocket connection closes abnormally with error code 1006.

**Screenshots**
![ScreenShot_1](https://velociti.pls-finger.me/Kta8vq.png)
![ScreenShot_2](https://velociti.pls-finger.me/0cYjbx.png)
![Screenshot_3](https://velociti.pls-finger.me/F8bXF0.png)

**Additional context**
If tried to make an authorization header request, Handshake invalid error is thrown.

**Comment by Tari-dev** [comment]
This is heroku issue with web apps : https://devcenter.heroku.com/articles/error-codes#h15-idle-connection

It can be fixed by running lavalink as worker along with a front web end

**Comment by 0zul** [comment]
Fixed
